# Generated by Django 4.1 on 2025-08-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('solvency', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Платежеспособность')),
            ],
            options={
                'verbose_name': 'Должник',
                'verbose_name_plural': 'Должники',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=200, verbose_name='Валюта')),
                ('date_start_time', models.TimeField(blank=True, null=True, verbose_name='Время создания')),
                ('date_start_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.debtor', verbose_name='Должник')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['date_end'],
            },
        ),
    ]
