# Generated by Django 4.1 on 2024-12-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_rent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='debtor',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='Debtor',
        ),
    ]
