# Generated by Django 4.1 on 2025-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_debtor_exchangerate_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='scale',
            field=models.IntegerField(default=1, verbose_name='Масштаб'),
        ),
    ]
